version: '3'
services:
  my-app:
    # build: .
    image: ${APP_IMAGE}
    ports:
     - 3000:3000
    environment:
     - MONGO_DB_USERNAME=${MONGO_DB_USERNAME}
     - MONGO_DB_PWD=${MONGO_DB_PWD}
  mongodb:
    image: mongo
    ports:
     - 27017:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USERNAME}
     - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PWD}
  mongo-express:
    image: mongo-express
    restart: always
    ports:
     - 8081:8081
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_DB_USERNAME}
     - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_DB_PWD}
     - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
     - "mongodb"